//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLCITests.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinEvent
    {
        public int Id { get; set; }
        public string BinId { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> EventDateTime { get; set; }
        public string ValidationState { get; set; }
        public string EventJson { get; set; }
        public string ValidationStateJson { get; set; }
    }
}
