//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLCITests.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinInventory
    {
        public int Id { get; set; }
        public string BinId { get; set; }
        public Nullable<int> UnitQty { get; set; }
        public string Uom { get; set; }
        public string UnitSize { get; set; }
        public string TermLength { get; set; }
        public string CurrentLocationType { get; set; }
        public string CurrentStatusType { get; set; }
        public string ValidationState { get; set; }
        public string WarehouseNbr { get; set; }
        public string WarehouseSublocation { get; set; }
        public string BinOriginJson { get; set; }
        public string BinDestinationJson { get; set; }
        public string BinJson { get; set; }
        public string ValidationStateJson { get; set; }
    }
}
