//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLCITests.Utilities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LCIEntities : DbContext
    {
        public LCIEntities()
            : base("name=LCIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinEvent> BinEvents { get; set; }
        public virtual DbSet<BinInventory> BinInventories { get; set; }
        public virtual DbSet<PrePackInspection> PrePackInspections { get; set; }
    }
}
