//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLCITests.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrePackInspection
    {
        public int Id { get; set; }
        public int PreReceivingTagNbr { get; set; }
        public string RanchNbr { get; set; }
        public string Block { get; set; }
        public Nullable<System.DateTime> ReceiptStartDate { get; set; }
        public Nullable<System.DateTime> ReceiptEndDate { get; set; }
        public string Status { get; set; }
        public string RanchBlockJson { get; set; }
        public string InspectionJson { get; set; }
        public Nullable<System.DateTime> EventTimeStamp { get; set; }
    }
}
